services:
  dev:
    platform: linux/amd64
    build:
      context: .
    volumes:
      - .:/workspace:cached
      - deps:/deps
      - cargo-registry:/root/.cargo/registry
      - cargo-git:/root/.cargo/git
      - target:/workspace/target
    working_dir: /workspace
    tty: true
    stdin_open: true

volumes:
  deps:
  cargo-registry:
  cargo-git:
  target:
