services:
  dev:
    platform: linux/amd64
    build:
      context: .
    environment:
      WORKSPACE: /workspace
      DEPS_DIR: /deps
      LOCAL_EXAFMM_DIR: /workspace/external/exafmm-t
      LOCAL_BEMPP_DIR: /workspace/external/bempp-cl
      LOCAL_KIFMM_DIR: /workspace/external/kifmm-for-rsrs
      BEMPP_KIFMM_ROOT: /workspace/external/kifmm-for-rsrs
    volumes:
      - .:/workspace:cached
      - deps:/deps
      - cargo-registry:/root/.cargo/registry
      - cargo-git:/root/.cargo/git
      - target:/workspace/target
    working_dir: /workspace
    tty: true
    stdin_open: true

volumes:
  deps:
  cargo-registry:
  cargo-git:
  target:
