#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

WORKSPACE="${WORKSPACE:-$REPO_ROOT}"
DEPS_DIR="${DEPS_DIR:-$WORKSPACE/.deps}"
LOCAL_EXAFMM_DIR="${LOCAL_EXAFMM_DIR:-$WORKSPACE/external/exafmm-t}"
LOCAL_BEMPP_DIR="${LOCAL_BEMPP_DIR:-$WORKSPACE/external/bempp-cl}"
LOCAL_KIFMM_DIR="${LOCAL_KIFMM_DIR:-$WORKSPACE/external/kifmm-for-rsrs}"
BUILD_RUST_PROJECT="${BUILD_RUST_PROJECT:-1}"
EXAFMM_PREFIX="${EXAFMM_PREFIX:-$DEPS_DIR/exafmm-prefix}"
PYTHON_BIN="${PYTHON_BIN:-}"
ENABLE_EXAFMM="${ENABLE_EXAFMM:-auto}"

if [ "$ENABLE_EXAFMM" = "auto" ]; then
  case "$(uname -s)" in
    Darwin) ENABLE_EXAFMM=0 ;;
    *) ENABLE_EXAFMM=1 ;;
  esac
fi

if [ -z "$PYTHON_BIN" ]; then
  if command -v python3.10 >/dev/null 2>&1; then
    PYTHON_BIN="python3.10"
  elif command -v python3 >/dev/null 2>&1; then
    PYTHON_BIN="python3"
  else
    echo "[setup] ERROR: python3.10 or python3 is required to create the virtual environment"
    exit 1
  fi
fi

echo "[setup] pwd before cd: $(pwd)"
echo "[setup] Using WORKSPACE=$WORKSPACE"
echo "[setup] Using DEPS_DIR=$DEPS_DIR"
echo "[setup] Using LOCAL_EXAFMM_DIR=$LOCAL_EXAFMM_DIR"
echo "[setup] Using LOCAL_BEMPP_DIR=$LOCAL_BEMPP_DIR"
echo "[setup] Using LOCAL_KIFMM_DIR=$LOCAL_KIFMM_DIR"
echo "[setup] BUILD_RUST_PROJECT=$BUILD_RUST_PROJECT"
echo "[setup] Using EXAFMM_PREFIX=$EXAFMM_PREFIX"
echo "[setup] Using PYTHON_BIN=$PYTHON_BIN"
echo "[setup] ENABLE_EXAFMM=$ENABLE_EXAFMM"

mkdir -p "$DEPS_DIR"
cd "$WORKSPACE"
echo "[setup] pwd after cd: $(pwd)"

cpu_count() {
  if command -v nproc >/dev/null 2>&1; then
    nproc
  elif command -v sysctl >/dev/null 2>&1; then
    sysctl -n hw.ncpu
  else
    echo 1
  fi
}

prepend_path_var() {
  local var_name="$1"
  local path_entry="$2"
  local current_value="${!var_name:-}"

  if [ -z "$current_value" ]; then
    printf -v "$var_name" "%s" "$path_entry"
  elif [ ":$current_value:" != *":$path_entry:"* ]; then
    printf -v "$var_name" "%s" "$path_entry:$current_value"
  fi

  export "$var_name"
}

kifmm_library_name() {
  case "$(uname -s)" in
    Darwin) echo "libkifmm.dylib" ;;
    MINGW*|MSYS*|CYGWIN*|Windows_NT) echo "kifmm.dll" ;;
    *) echo "libkifmm.so" ;;
  esac
}

source_tree_newer_than_marker() {
  local source_dir="$1"
  local marker="$2"

  if [ ! -f "$marker" ]; then
    return 0
  fi

  if find "$source_dir" \
    \( -path "$source_dir/.git" -o -path "$source_dir/target" -o -path "$source_dir/.venv" -o -path "$source_dir/.eggs" -o -path "$source_dir/build" -o -path "$source_dir/dist" -o -name "__pycache__" -o -name "*.egg-info" \) -prune \
    -o -type f -newer "$marker" -print -quit | grep -q .; then
    return 0
  fi

  return 1
}

sync_source_tree() {
  local source_dir="$1"
  local dest_dir="$2"

  rm -rf "$dest_dir"
  mkdir -p "$dest_dir"

  tar -C "$source_dir" \
    --exclude=.git \
    --exclude=.eggs \
    --exclude=build \
    --exclude=dist \
    --exclude='*.egg-info' \
    --exclude='__pycache__' \
    --exclude='*.pyc' \
    -cf - . | tar -C "$dest_dir" -xf -
}

configure_kifmm_runtime_env() {
  local kifmm_root="$1"
  local kifmm_lib="$kifmm_root/target/release/$(kifmm_library_name)"

  export BEMPP_KIFMM_ROOT="$kifmm_root"
  export KIFMM_ROOT="$kifmm_root"

  if [ -f "$kifmm_lib" ]; then
    export BEMPP_KIFMM_LIBRARY="$kifmm_lib"
    export KIFMM_LIBRARY="$kifmm_lib"
  else
    unset BEMPP_KIFMM_LIBRARY || true
    unset KIFMM_LIBRARY || true
  fi

  echo "[setup] BEMPP_KIFMM_ROOT=$BEMPP_KIFMM_ROOT"
  if [ -n "${BEMPP_KIFMM_LIBRARY:-}" ]; then
    echo "[setup] BEMPP_KIFMM_LIBRARY=$BEMPP_KIFMM_LIBRARY"
  fi
}

configure_exafmm_runtime_env() {
  local exafmm_prefix="$1"

  export EXAFMM_PREFIX="$exafmm_prefix"
  prepend_path_var CPATH "$exafmm_prefix/include"
  prepend_path_var C_INCLUDE_PATH "$exafmm_prefix/include"
  prepend_path_var CPLUS_INCLUDE_PATH "$exafmm_prefix/include"
  prepend_path_var LIBRARY_PATH "$exafmm_prefix/lib"
  prepend_path_var PKG_CONFIG_PATH "$exafmm_prefix/lib/pkgconfig"

  case "$(uname -s)" in
    Darwin) prepend_path_var DYLD_LIBRARY_PATH "$exafmm_prefix/lib" ;;
    *) prepend_path_var LD_LIBRARY_PATH "$exafmm_prefix/lib" ;;
  esac

  echo "[setup] EXAFMM_PREFIX=$EXAFMM_PREFIX"
}

write_local_env_file() {
  local env_file="$WORKSPACE/.rsrs-env.sh"

  {
    printf '#!/usr/bin/env bash\n'
    printf '# Generated by scripts/setup_deps.sh. Source this after activating .venv.\n'
    printf 'export RSRS_WORKSPACE="%s"\n' "$WORKSPACE"
    printf 'export PYTHON_INCLUDE_DIR="%s"\n' "$PYTHON_INCLUDE_DIR"
    printf 'export PYTHON_LIB_DIR="%s"\n' "$PYTHON_LIB_DIR"
    printf 'export BEMPP_KIFMM_ROOT="%s"\n' "$BEMPP_KIFMM_ROOT"
    printf 'export KIFMM_ROOT="%s"\n' "$KIFMM_ROOT"
    if [ -n "${BEMPP_KIFMM_LIBRARY:-}" ]; then
      printf 'export BEMPP_KIFMM_LIBRARY="%s"\n' "$BEMPP_KIFMM_LIBRARY"
      printf 'export KIFMM_LIBRARY="%s"\n' "$KIFMM_LIBRARY"
    fi
    cat <<'EOF'
export PATH="$RSRS_WORKSPACE/.venv/bin${PATH:+:$PATH}"
export PYTHONPATH="$RSRS_WORKSPACE${PYTHONPATH:+:$PYTHONPATH}"
EOF

    if [ "$ENABLE_EXAFMM" = "1" ]; then
      printf 'export EXAFMM_PREFIX="%s"\n' "$EXAFMM_PREFIX"
      cat <<'EOF'
export CPATH="$EXAFMM_PREFIX/include${CPATH:+:$CPATH}"
export C_INCLUDE_PATH="$EXAFMM_PREFIX/include${C_INCLUDE_PATH:+:$C_INCLUDE_PATH}"
export CPLUS_INCLUDE_PATH="$EXAFMM_PREFIX/include${CPLUS_INCLUDE_PATH:+:$CPLUS_INCLUDE_PATH}"
export LIBRARY_PATH="$EXAFMM_PREFIX/lib${LIBRARY_PATH:+:$LIBRARY_PATH}"
export PKG_CONFIG_PATH="$EXAFMM_PREFIX/lib/pkgconfig${PKG_CONFIG_PATH:+:$PKG_CONFIG_PATH}"
EOF

      case "$(uname -s)" in
        Darwin)
          cat <<'EOF'
export DYLD_LIBRARY_PATH="$EXAFMM_PREFIX/lib${DYLD_LIBRARY_PATH:+:$DYLD_LIBRARY_PATH}"
EOF
          ;;
        *)
          cat <<'EOF'
export LD_LIBRARY_PATH="$EXAFMM_PREFIX/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
EOF
          ;;
      esac
    fi
  } > "$env_file"

  chmod 0644 "$env_file"
  echo "[setup] Wrote reusable environment exports to $env_file"
}

base_python_has_pip() {
  "$PYTHON_BIN" -m pip --version >/dev/null 2>&1
}

ensure_virtualenv_available() {
  if "$PYTHON_BIN" -m virtualenv --version >/dev/null 2>&1; then
    return 0
  fi

  if ! base_python_has_pip; then
    echo "[setup] ERROR: $PYTHON_BIN can create a virtual environment but cannot bootstrap pip or virtualenv."
    echo "[setup] Install pip/virtualenv for the base interpreter first, or pass --python to a different interpreter."
    exit 1
  fi

  echo "[setup] Installing virtualenv for fallback venv bootstrap"
  "$PYTHON_BIN" -m pip install --user virtualenv >/dev/null
}

venv_is_usable() {
  [ -f ".venv/bin/activate" ] && .venv/bin/python -m pip --version >/dev/null 2>&1
}

create_venv_with_fallback() {
  echo "[setup] Creating Python venv in $WORKSPACE/.venv"
  rm -rf .venv
  "$PYTHON_BIN" -m venv .venv || true

  if venv_is_usable; then
    return 0
  fi

  echo "[setup] Built-in venv bootstrap was incomplete; retrying with virtualenv"
  rm -rf .venv
  ensure_virtualenv_available
  "$PYTHON_BIN" -m virtualenv -p "$PYTHON_BIN" .venv

  if ! venv_is_usable; then
    echo "[setup] ERROR: failed to create a usable virtual environment in $WORKSPACE/.venv"
    exit 1
  fi
}

require_local_checkout() {
  local path="$1"
  local label="$2"
  local hint="$3"
  local expected_file="$4"

  if [ ! -d "$path" ]; then
    echo "[setup] ERROR: expected $label at $path"
    echo "[setup] $hint"
    exit 1
  fi

  if [ ! -e "$path/$expected_file" ]; then
    echo "[setup] ERROR: $label at $path is missing $expected_file"
    echo "[setup] $hint"
    exit 1
  fi
}

# --- Python venv bootstrap ---
VENV_CREATED=0
if [ ! -x ".venv/bin/python" ] || ! venv_is_usable; then
  create_venv_with_fallback
  VENV_CREATED=1
fi

# shellcheck disable=SC1091
source .venv/bin/activate

echo "[setup] Python: $(python --version)"
python -m pip install -U pip >/dev/null
python -m pip install -U uv maturin >/dev/null
export UV_LINK_MODE=copy

export PYTHON_INCLUDE_DIR="$(python -c "import sysconfig; print(sysconfig.get_paths()['include'])")"
export PYTHON_LIB_DIR="$(python -c "import sysconfig; print(sysconfig.get_config_var('LIBDIR') or '')")"

echo "[setup] PYTHON_INCLUDE_DIR=$PYTHON_INCLUDE_DIR"
echo "[setup] PYTHON_LIB_DIR=$PYTHON_LIB_DIR"

# --- Ensure gmsh is available inside the venv ---
TARGET_GMSH="$WORKSPACE/.venv/bin/gmsh"
SYS_GMSH="$(command -v gmsh || true)"

if [ -x "$TARGET_GMSH" ]; then
  echo "[setup] Using gmsh from venv: $TARGET_GMSH"
elif [ -n "$SYS_GMSH" ]; then
  echo "[setup] Linking system gmsh into venv: $SYS_GMSH"
  rm -f "$TARGET_GMSH"
  ln -s "$SYS_GMSH" "$TARGET_GMSH"
else
  echo "[setup] gmsh not found on PATH; installing the Python gmsh package into the venv"
  python -m pip install gmsh >/dev/null
fi

if [ ! -x "$TARGET_GMSH" ]; then
  echo "[setup] ERROR: gmsh is still unavailable after setup."
  echo "[setup] Install a system gmsh binary, or ensure 'python -m pip install gmsh' succeeds for the chosen interpreter."
  exit 1
fi

# --- exafmm-t ---
if [ "$ENABLE_EXAFMM" = "1" ]; then
  require_local_checkout \
    "$LOCAL_EXAFMM_DIR" \
    "exafmm-t checkout" \
    "Run 'git submodule update --init --recursive' so the external repositories are available." \
    "setup.py"

  EXAFMM_SOURCE_DIR="$LOCAL_EXAFMM_DIR"
  EXAFMM_BUILD_DIR="$DEPS_DIR/exafmm-t"
  EXAFMM_INSTALL_MARKER="$DEPS_DIR/.exafmm_installed.ok"
  EXAFMM_INSTALL_SOURCE_FILE="$DEPS_DIR/.exafmm_install_source"
  EXAFMM_INSTALL_PREFIX_FILE="$DEPS_DIR/.exafmm_install_prefix"
  EXAFMM_INSTALL_SOURCE="$EXAFMM_SOURCE_DIR"
  EXAFMM_PREVIOUS_SOURCE="$(cat "$EXAFMM_INSTALL_SOURCE_FILE" 2>/dev/null || true)"
  EXAFMM_PREVIOUS_PREFIX="$(cat "$EXAFMM_INSTALL_PREFIX_FILE" 2>/dev/null || true)"

  configure_exafmm_runtime_env "$EXAFMM_PREFIX"

  if [ "$VENV_CREATED" = "1" ] || [ "$EXAFMM_PREVIOUS_SOURCE" != "$EXAFMM_INSTALL_SOURCE" ] || [ "$EXAFMM_PREVIOUS_PREFIX" != "$EXAFMM_PREFIX" ] || source_tree_newer_than_marker "$EXAFMM_SOURCE_DIR" "$EXAFMM_INSTALL_MARKER"; then
    echo "[setup] Staging exafmm-t from submodule checkout at $LOCAL_EXAFMM_DIR"
    sync_source_tree "$EXAFMM_SOURCE_DIR" "$EXAFMM_BUILD_DIR"
    echo "[setup] Building & installing exafmm-t"
    pushd "$EXAFMM_BUILD_DIR" >/dev/null
    mkdir -p "$EXAFMM_PREFIX"
    CFLAGS="-O3" CXXFLAGS="-O3" ./configure --prefix="$EXAFMM_PREFIX"
    make -j"$(cpu_count)"
    make install
    python -m pip install .
    popd >/dev/null
    printf '%s\n' "$EXAFMM_INSTALL_SOURCE" > "$EXAFMM_INSTALL_SOURCE_FILE"
    printf '%s\n' "$EXAFMM_PREFIX" > "$EXAFMM_INSTALL_PREFIX_FILE"
    touch "$EXAFMM_INSTALL_MARKER"
  fi
else
  echo "[setup] Skipping exafmm-t setup on this platform."
  echo "[setup] ExaFMM is not supported on macOS hosts; use KiFMM, dense assembly, or Docker/linux for ExaFMM runs."
fi

# ---- h5py (build from source against system HDF5) ----
if [ "$VENV_CREATED" = "1" ] || [ ! -f "$DEPS_DIR/.h5py_installed.ok" ]; then
  echo "[setup] Installing h5py into venv from source"
  uv pip install --no-binary=h5py h5py
  touch "$DEPS_DIR/.h5py_installed.ok"
fi

# ---- bempp-cl (prefers vendored source in this repo) ----
require_local_checkout \
  "$LOCAL_BEMPP_DIR" \
  "bempp-cl checkout" \
  "Run 'git submodule update --init --recursive' so the external repositories are available." \
  "pyproject.toml"

BEMPP_INSTALL_SOURCE="$LOCAL_BEMPP_DIR"

if [ "$VENV_CREATED" = "1" ] || [ ! -f "$DEPS_DIR/.bempp_installed.ok" ] || [ "$(cat "$DEPS_DIR/.bempp_installed.ok" 2>/dev/null || true)" != "$BEMPP_INSTALL_SOURCE" ]; then
  echo "[setup] Installing bempp-cl from submodule checkout at $LOCAL_BEMPP_DIR"
  uv pip install -e "$LOCAL_BEMPP_DIR"
  echo "$BEMPP_INSTALL_SOURCE" > "$DEPS_DIR/.bempp_installed.ok"
fi

# ---- kifmm-for-rsrs (from checked-out submodule) ----
require_local_checkout \
  "$LOCAL_KIFMM_DIR" \
  "kifmm-for-rsrs checkout" \
  "Run 'git submodule update --init --recursive' so the external repositories are available." \
  "kifmm/pyproject.toml"

KIFMM_SOURCE_DIR="$LOCAL_KIFMM_DIR"

KIFMM_INSTALL_MARKER="$DEPS_DIR/.kifmm_installed.ok"
KIFMM_INSTALL_SOURCE_FILE="$DEPS_DIR/.kifmm_install_source"
KIFMM_INSTALL_SOURCE="$KIFMM_SOURCE_DIR"
KIFMM_PREVIOUS_SOURCE="$(cat "$KIFMM_INSTALL_SOURCE_FILE" 2>/dev/null || true)"

if [ "$VENV_CREATED" = "1" ] || [ "$KIFMM_PREVIOUS_SOURCE" != "$KIFMM_INSTALL_SOURCE" ] || source_tree_newer_than_marker "$KIFMM_SOURCE_DIR" "$KIFMM_INSTALL_MARKER"; then
  echo "[setup] Building & installing kifmm-for-rsrs from submodule checkout at $LOCAL_KIFMM_DIR"
  pushd "$KIFMM_SOURCE_DIR/kifmm" >/dev/null
  maturin develop --release
  popd >/dev/null
  printf '%s\n' "$KIFMM_INSTALL_SOURCE" > "$KIFMM_INSTALL_SOURCE_FILE"
  touch "$KIFMM_INSTALL_MARKER"
fi

configure_kifmm_runtime_env "$KIFMM_SOURCE_DIR"
write_local_env_file

# ---- Build main Rust project (optional on startup) ----
if [ "$BUILD_RUST_PROJECT" = "1" ]; then
  echo "[setup] Building Rust project"
  cargo build
else
  echo "[setup] Skipping top-level Rust build on startup"
fi

# If no command was provided (common with some compose setups), default to bash.
if [ "$#" -eq 0 ]; then
  exec bash
else
  exec "$@"
fi
