#[derive(Clone, strum_macros::AsRefStr, strum_macros::EnumString, Debug, serde::Deserialize)]
pub enum StructuredOperatorType {
    BaseStructuredOperator,
    BasicStructuredOperator,
    BemppClLaplaceSingleLayer,
    BemppClHelmholtzSingleLayer,
    KiFMMLaplaceOperator,
    KiFMMHelmholtzOperator,
    BemppRsLaplaceOperator,
    BemppClLaplaceCombined,
    BemppClLaplaceSecond,
    BemppClLaplaceSingleLayerCP,
    BemppClLaplaceSingleLayerMM,
    BemppClHelmholtzSingleLayerCP,
    BemppClLaplaceSingleLayerCPID,
    BemppClLaplaceSingleLayerP1,
    KiFMMLaplaceOperatorV,
    BemppClLaplaceCombinedP1,
    BemppClLaplaceSingleLayerCPIDP1,
    BemppClHelmholtzSingleLayerCPID,
    BemppClMaxwellEfie,
    BemppClHelmholtzSingleLayerP1,
    BemppClBurtonMiller,
    BemppClHelmholtzCombined,
    BIEGrid,
}
